### ISSUE TITLE
Composer Download page haven't updated checksum.

### ISSUE THREAD

**Issue by mekanixdk** [composer/getcomposer.org#149] opened 2020-02-12 12:46 UTC
My `composer.json`:

```json
N/A
```

Output of `composer diagnose`:

```
N/A
```

When I run this command:

```
php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
php -r "if (hash_file('sha384', 'composer-setup.php') === 'c5b9b6d368201a9db6f74e2611495f369991b72d9c8cbd3ffbc63edff210eb73d46ffbfce88669ad33695ef77dc76976') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
```

I get the following output:

```
Installer corrupt
```

And I expected this to happen:

Composer installed. I looks like the checksum haven't been updated here https://getcomposer.org/download/ after the latest release.

**Comment by alcohol** [comment] 2020-02-12 16:14
Duplicate of #148

**Closed by alcohol** 2020-02-12 16:14 UTC

**Comment by Seldaek** [comment] 2020-02-12 17:32
Fixed now sorry about that.
